### ISSUE TITLE
About "korayucar/vaadin-components"

### ISSUE THREAD

**Issue by jouni** [korayucar/gitcms#1]
Sorry for posting a completely off-topic question in this repository, but this seemed like the only way I could get in touch with you.

We were wondering if you could perhaps remove your fork of the old vaadin-components project (now named vaadin-elements, soon vaadin-core-elements), as it is showing up in customelements.io when you search for "vaadin": https://customelements.io/search/vaadin

If you still want to keep the fork, could you at least update it and rename the repository to begin with some other prefix than "vaadin"?

Have you registered your fork in Bower? If you have, I would like to request you to unregister that, as "vaadin" is a registered trademark and we would like to own that namespace for our Web Components.

I hope you have to time to consider this. Thanks in advance!

**Comment by korayucar** [comment]
Sorry for the inconvenience. I deleted the fork.

**Comment by jouni** [comment]
Well, that was fast! Thank you very much :bow: 

I will contact the developers of customelements.io if it still hangs around there after a while.
